### ISSUE TITLE
Update - Extended variables support

### ISSUE THREAD

**Issue by Bouh** [4ian/GDevelop-extensions#107]
Here an update for update my **Extended variables support** extension.

- [x] Use const, let instead var.
- [x] Improve descriptions.
- [x] Align the extension on the best pratice.
- New expressions:
   - [x]  `ExtendedVariables::Variable(name)` Return the value of a scene variable.
   - [x] `ExtendedVariables::GlobalVariable(name)` Return the value of a global variable.
   - [x]  `ExtendedVariables::VariableString(name)` Return the text of a scene variable.
   - [x]  `ExtendedVariables::GlobalVariableString(name)` Return the text of a global variable.
- New actions:
   - [x]  Modify a global variable with a value.
   - [x]  Modify a scene variable with a value.
   - [x]  Modify a global variable with a text.
   - [x]  Modify a scene variable with a text.
   
Why these new expressions and actions?
Because in an variable field we can't write expressions.
For example we want create a variable named "Countdown123", and 123 is the value from the parameters in an action extension.
Here how we allow the user to create their variable, and below how it's not possible.

![image](https://user-images.githubusercontent.com/1670670/110402262-63491a00-807b-11eb-882f-2062e703f645.png)

These new expressions and actions use the GDJS API, this mean all is compatible with current variables, there is no differences.

If theses new expression and actions are not approved because this it should be supported in the engine i'm ok with that. In this case i'll only update the other points of the checklist.

Here the current state of the extension in a project, with the example shown on the screen.
(There is also another extension about timers in this project, forget it)
[countdownTimer.zip](https://github.com/4ian/GDevelop-extensions/files/6105127/countdownTimer.zip)

**Comment by 4ian** [comment]
> Here how we allow the user to create their variable, and below how it's not possible.

It's ok to do that in this extension :) I prefer to keep it in a separate extension because in general I want to make this kind of "dynamic" handling discouraged for "top level variables" (i.e: you can't just write `"My" + "Variable"` for a variable, but you can write it for a child of a structure: `MyStructure["My" + "Child"]`) - this way dynamic constructions are possible but we can have in the future error handling (You've used a variable called MyVariable, but there is one named myvariable in the list - did you make a mistake?).
This kind of "static checking" is not possible with fully dynamic variable names.
It's ok as you long as you know that you lose this capacity in the future, which is why I'm ok having this but in an "opt-in" extension.
