### ISSUE TITLE
MousePointerLockExtension

### ISSUE THREAD

**Issue by PANDAKO-GitHub** [4ian/GDevelop-extensions#114]
## Describe the extension
This behavior removes the limit on the distance the mouse can move and hides the cursor.
For example, a user can rotate or continue to manipulate an object by moving the mouse endlessly.
Without the pointer lock, the rotation or operation will stop the moment the pointer reaches the edge of the browser or screen.
Game players don't have to worry about leaving the gameplay area or accidentally clicking on another application that moves the mouse focus away from the game.

Locking the pointer locks MouseX() and MouseY().
Use MovementX() and MovementY() instead.

## Checklist

- [x] Extension has a proper name and description.
- [x] Extension has tags (for example: "platform, brick, breakable").
- [x] All behaviors have a description.
- [x] All functions (actions, conditions, expressions) have descriptions and proper sentences.
- [x] I've followed the best practices listed on http://wiki.compilgames.net/doku.php/gdevelop5/extensions/best-practices
- [x] I confirm that this extension can be intergrated to this GitHub repository, distributed and MIT licensed.

## Extension file
[MousePointerLockExtension0.1.1.zip](https://github.com/4ian/GDevelop-extensions/files/6194961/MousePointerLockExtension0.1.1.zip)

## Repository
https://github.com/PANDAKO-GitHub/MousePointerLockExtension

## Sample
https://pandako-github.github.io/MousePointerLockExtension/

**Comment by Bouh** [comment]
Thank this can be very helpful.
I've made some change on descriptions for follow [the best pratices](http://wiki.compilgames.net/doku.php/gdevelop5/extensions/best-practices) of extensions.
I've bumped the version of the extension tp 0.1.2 with this changes:
- JS code is formated
- JS variable return 0 if the value is not found for movement X and Y.
- Icon added on the extension.
- Markdown syntax added on the description of the extension for expressions.
- const used in onFirstSceneLoaded, because we can, this method is called only once.

One doubt I see you get the first element canvas by the tag name in the page. This can be wrong in some case where the game is include on a web page with others canvas element.
@4ian can we see for add a unique ID on the canvas html element, like 'GDevelop-Game-Engine' ?


[MousePointerLockExtension0.1.2.zip](https://github.com/4ian/GDevelop-extensions/files/6200188/MousePointerLockExtension0.1.2.zip)

**Comment by 4ian** [comment]
Very nice extension! 

Thanks Bouh for all the additions.

> @4ian can we see for add a unique ID on the canvas html element, like 'GDevelop-Game-Engine' ?

I think you could even use `runtimeGame.getRenderer().getCanvas()`?

**Comment by PANDAKO-GitHub** [comment]
@Bouh thank you for improving😄

**Comment by PANDAKO-GitHub** [comment]
@4ian thank you for your advice.😊

> I think you could even use `runtimeGame.getRenderer().getCanvas()`?

I made this change and it worked fine.🙌

```javascript
const canvas = runtimeScene.getGame().getRenderer().getCanvas();
```

I created v0.1.3 using v0.1.2.

[MousePointerLockExtension0.1.3.zip](https://github.com/4ian/GDevelop-extensions/files/6201703/MousePointerLockExtension0.1.3.zip)

**Comment by Bouh** [comment]
Thx guys!
The extension has been added :)
Commit https://github.com/4ian/GDevelop-extensions/commit/e63e939d06dc981f9a4ed5f74187fa13702ddc57

**Comment by 4ian** [comment]
Great work, thanks all! 👍👍

**Comment by tristanbob** [comment]
I just tried installing this extension and I get the "Unable to download and install extension" error.

**Comment by 4ian** [comment]
Should be fixed and safety checks added against the mistake in the extension name :)
