### ISSUE TITLE
New Extension - Is On Screen detection 

### ISSUE THREAD

**Issue by Silver-Streak** [4ian/GDevelop-extensions#134]
## Describe the extension
This extension adds conditions to check if an object is currently located within the visible portion of its layer's camera. The condition also allows for specifying padding to the virtual screen border.

As each layer has a unique camera, this will only work for the layer that the object is on. This does not take into account any object visibility, such as being hidden or 0 opacity, but can be combined with those existing conditions.

This uses the object's boundary box for detection, due to this objects with modified origin points may not behave as expected.

This helps simplify detecting if an object is on the screen, and avoids workarounds involving a "On Screen" object and using collision detection, potentially helping with performance.

## Checklist

- [x] Extension has a proper name and description.
- [x] Extension has tags (for example: "platform, brick, breakable").
- [x] All behaviors have a description.
- [x] All functions (actions, conditions, expressions) have descriptions.
- [x] I confirm that this extension can be intergrated to this GitHub repository, distributed and MIT licensed.

## Extension file

Extension File: [IsOnScreenExtension.zip](https://github.com/4ian/GDevelop-extensions/files/6412201/IsOnScreenExtension.zip)
Example project: 
[IsOnScreen Example Project.zip](https://github.com/4ian/GDevelop-extensions/files/6412203/IsOnScreen.Example.Project.zip)

**Comment by D8H** [comment]
> _PARAM1_ is currently on screen of its current layer's camera padded by _PARAM2_ pixels

I think that current is always implied and the layer is an implementation matter. Maybe something like this?
_PARAM1_ is on screen with a padding of _PARAM2_ pixels

> This uses the object's boundary box for detection, due to this objects with modified origin points may not behave as expected.

I guess this could be solved using the AABB with a Javascript event.

I think that adding conditions for entering and leaving the screen could be useful. Maybe even for top, bottom, left and right.

**Comment by Silver-Streak** [comment]
> I think that "current" is always implied and the layer is an implementation matter. Maybe something like this?
> _PARAM1_ is on screen with a padding of _PARAM2_ pixels
Based off the conversation from the discord, enough users don't understand that cameras are layer specific that I feel like calling it out will help avoid confusion. Although if there is a strong disagreement I can update that.

> I guess this could be solved using the AABB with a Javascript event.
Unless someone with strong understanding of the AABB/boundary box functionality and Javascript wants to add this, it would be outside of my current skillset. 

> I think that adding conditions for entering and leaving the screen could be useful. Maybe even for top, bottom, left and right.

I feel like most of these are already addressable using variables along with the conditions I've created, and am not sure how much value adding more would create, but let me take a look and see what's feasible.

**Comment by Lim98SE** [comment]
oh thank god this exists

**Comment by Bouh** [comment]
It's work fine except when the camera is rotated.

**Comment by Silver-Streak** [comment]
> It's works fine except when the camera is rotated.

I haven't had time to look at this at all this week, can you tell me what does/doesn't work? Does the detection just change to no longer being accurate for the borders, or just not work at all?

**Comment by Bouh** [comment]
I've found a solution, it wasn't simple, i've added comment on each line of my code.
Sorry it's not made with events, isn't possible some fonction to convert are missing or I don't know them.
It was simplier to me in JS.

So you can try, it take care of camera rotation, camera zoom, and padding still exist if needed.
I've edited the long description for it, check it, it was important to precise the orientation of padding.

It's not perfect in the case where the sprite (in red) is outside the screen but the aabb/bounding box is (blue).
![image](https://user-images.githubusercontent.com/1670670/118045466-39acb780-b378-11eb-95b6-2df2acefc0c9.png)

It's still better than nothing i guess.
I'm done with math today.

[Project_v2.zip](https://github.com/4ian/GDevelop-extensions/files/6469140/v2.zip)

**Comment by Bouh** [comment]
Let me know after tried if you think it's fine.
If yes I'll review it one last time and approve your extension.

**Comment by Silver-Streak** [comment]
Bouh's changes  make this WAY more flexible. Note: For it to work accurately you need to be on b110, it does not work accurately in b108. 

I can't find a great way to make the requested additional checks that @D8H asked for, but I've made updates to the descriptions throughout the extension, and updated the author field to give Bouh credit since the events are entirely his design now.

[IsOnScreen1dot1.zip](https://github.com/4ian/GDevelop-extensions/files/6481423/IsOnScreen1dot1.zip)

**Comment by Bouh** [comment]
Thanks both for your time!

This extension is approved and merged! https://github.com/4ian/GDevelop-extensions/commit/b43a4d0394c879bf1bb4e911a0044de255d76bee

**Comment by 4ian** [comment]
I've checked the extension, I think JS is the way to go indeed to use AABB for objects. But there are usages of private functions:
`runtimeScene._updateLayersCameraCoordinates`

This **will** break in the future. Remember that it's not a question of "maybe it's not a problem that I used a private function of GDJS, it's working", it's not a "if" it breaks, but "when" it will break. And it will and it will be painful for me or you to make an emergency fix to the extension after releasing an extension, and it will be a pain for users that will be worried of upgrading GDevelop.

Instead, compute the coordinates of the camera using:
theLayer.getCameraX() - (theLayer.getCameraWidth() / 2)
theLayer.getCameraX() + (theLayer.getCameraWidth() / 2)
theLayer.getCameraY() - (theLayer.getCameraHeight() / 2)
theLayer.getCameraY() + (theLayer.getCameraHeight() / 2)

Zoom is already taken care of, so no need to use `layer.getCameraZoom()` (passing it to `_updateLayersCameraCoordinates` is not correct btw - another reason not for using private stuff ;)).

If we can fix this that would be great :) 

Sorry to be the party pooper, the extension is great otherwise, but it is really important to never ship any extension with a private function called, because it will basically break in the next version. If something is missing, ask me and we can expose something or find another workaround to design an API.

**Comment by Silver-Streak** [comment]
> Instead, compute the coordinates of the camera using:
> theLayer.getCameraX() - (theLayer.getCameraWidth() / 2)
> theLayer.getCameraX() + (theLayer.getCameraWidth() / 2)
> theLayer.getCameraY() - (theLayer.getCameraHeight() / 2)
> theLayer.getCameraY() + (theLayer.getCameraHeight() / 2)


Hmmm, isn't this what I was doing in my original version, just without JS (using in-event expressions). Is there a reason why the expressions didn't take layer rotation into account?

**Comment by Bouh** [comment]
I've found a solution without private function, and without all this stuff on camera.
It works with camera rotation, scale, and changed positions.

I let you try the project, if it's right to you guys i'll merge the fix.

[project_export.zip](https://github.com/4ian/GDevelop-extensions/files/6485751/project_export.zip)

[Test online](https://games.gdevelop-app.com/game-0d37143f-1780-4685-993a-0e1ba69ece61/index.html)

**Comment by 4ian** [comment]
Ah great Bouh! This is indeed the right and proper solution!

> Hmmm, isn't this what I was doing in my original version, just without JS (using in-event expressions). Is there a reason why the expressions didn't take layer rotation into account?

What I suggested (Using `theLayer.getCameraX() - (theLayer.getCameraWidth() / 2)`...) was like the previous solution of Bouh (but using no private methods) but you're right that it was not also the correct solution!

Let me recap:
- Your solution with event conditions had two issues: 1) they would not work entirely if the object is rotated (if rotated, they can be outside of their "box". The proper solution is to use the AABB (axis aligned bounding box) which takes into account the rotation (visible in blue when you use the action to draw the debug collision masks/AABB). and 2) it would also not work entirely if the layer is rotated. This is because of the same issue: with the rotation, the layer can show things that are not outside of the original "box" that you compute.
- The solution that was made originally by Bouh is using JS to get the AABB of an object. This way even if the object is rotated, the game engine will give you the box containing the whole object. It is *guaranteed* that your object is inside this box. **Problem:** the layer can be rotated too! It was not (and my solution was also not) taking this into account. 

So this means we should compute the AABB of the layer, and check for the intersection of the AABB... this is costly and not guaranteed, because AABB are "larger" than the layer and so your object could be somewhere inside the AABB. See:

![image](https://user-images.githubusercontent.com/1280130/118358819-8232c380-b578-11eb-9672-59e18409abb2.png)

With the new solution, we use the function to convert the AABB of the object to the "screen" coordinates. Then we can check if this AABB is inside the screen ("more than 0;0, less than game_width;game_height" in pseudocode):

![image](https://user-images.githubusercontent.com/1280130/118359037-667bed00-b579-11eb-8b8e-1f868382973a.png)


Which means all zoom/rotation/layer position is taken into account, and reduce the error by a lot (in case of a rotated object/layer, there is still a possibility of an object slightly out of the screen declared as shown - hence the usefuless of a negative padding if you want to be sure that your player can see it).

@Bouh the extension looks good, though could you:
- Remove the commented lines.
- Change `Get his layer to convert the coordinate of aabb to the world coordinates` to `Get the layer to convert the coordinates of the AABB to the screen coordinates` (**screen**, not world. world means the scene).
?

Also the condition seems to work only for one object.

**Comment by Bouh** [comment]
> Also the condition seems to work only for one object.

Yes, I use the first instance picked by events, should I iterate on each instance?
In this case I return true for is on screen in which case? When all instance are on screen, but what when one instance isn't and the other are still on screen? I return false because one on them is outside or false because it just one instance that isn't on screen.

**Comment by Bouh** [comment]
New update is merged v1.1.1 https://github.com/4ian/GDevelop-extensions/commit/6621e6d04cc9d157f3e4fd099bf7a6f6a573bfdf

**Comment by tristanbob** [comment]
I tried using this extension and it was acting strange when it was not inside a ForEach() loop.

I also think people would prefer to use this condition by selecting the object and searching for it's conditions (there won't be any since this is a stand-alone condition).

Therefore, I quickly converted this to behavior by copy-pasting and testing if it worked.  It seems to work great, but I would like the people that built this to test it also, please.  Thanks!

## Version 1.2.0

- Changed to a behavior 

## Extension file

[IsOnScreen_Extension_1.2.0.json.zip](https://github.com/4ian/GDevelop-extensions/files/6748917/IsOnScreen_Extension_1.2.0.json.zip)

**Comment by 4ian** [comment]
I've reopened this then, but maybe create another issue for this update?

**Comment by tristanbob** [comment]
In the future, I will create new issues when I update existing extensions. 

Part of the reason I bumped this post is so the people who helped make this can see the update and provide feedback. 

Does anyone have time to test this change (into a behavior)?

**Comment by 4ian** [comment]
Looks good I think! I've made a few small changes:

* "Checks if an object's position is within the viewport of its layer." => Too long for a behavior name I would say. I changed to simply "Is on screen".
* In the behavior description: "This extension [...]" => this is a behavior, not an extension ;) 
* "This uses the object's boundary box for detection, due to this objects with modified origin points may not behave as expected" => I think this is not the case anymore, as we're using the JS function to get the "AABB" of the object, which should be always valid.

I've pushed the changes :)
