### ISSUE TITLE
Back and forth movement

### ISSUE THREAD

**Issue by PascalLadalle** [4ian/GDevelop-extensions#14]
## Describe the extension
Back and forth movement behavior, horizontal or vertical, based on time or distance (the time setting is also a failsafe to avoid the objects getting stuck if the available distance is too short)

I think there's still a small bug left. Timers don't seem to be instance-specific for vertical movement. I couldn't find the cause.

## Checklist

- [x] Extension has a proper name and description.
- [x] Extension has tags (for example: "platform, brick, breakable").
- [x] All behaviors have a description.
- [x] All functions (actions, conditions, expressions) have descriptions.
- [x] I confirm that this extension can be intergrated to this GitHub repository, distributed and MIT licensed.

[ExtensionBaF.zip](https://github.com/4ian/GDevelop-extensions/files/3370642/ExtensionBaF.zip)

**Comment by 4ian** [comment]
Sorry for the delay, I still did not get a chance to look at this but will do at the beginning of the week :)

**Comment by 4ian** [comment]
I took a quick look at the events:

* There is an "Unknown or unsupported instruction" at the end, can you check/remove it?
* You don't need the "For each object"s. Behavior events in functions are already repeated separately for each different object having the behavior.
* The timer "timeout" will be created on the instances, but "timeout" is a quite generic name and there is a very high chance that this will one day conflict with a timer used by a user of this behavior - making a very hard to find and frustrating bug. Ideally, behavior would have their own timers, for now it's not the case, so can you instead use a long, specific name like "FlipBackAndForthMovemement_timeout"?
* Same for variables "startpoint", "distance" and "timeout"... these variables will conflict at some point with other variables. The soltuion? You already properly created properties, including a hidden property for the startpoint (that could have been named StartPosition, because it's not really a point, it's just a number). Use the action/condition/expression related to these properties to replace all the action/condition/expression dealing with variables.

Ideally a behavior is not using any variable and relying just on properties. This also allow to use the same behavior multiple time in the same object :)

**Comment by PascalLadalle** [comment]
I know 😞 I started out with properties, but at some point, the movements were not instance-specific, I blamed it on the properties and switched to variables (and sprinkled some _for each_ 😬 )... and I must have fixed my bug at the same time because it worked 😅 
Here's the new version.
[Extension.zip](https://github.com/4ian/GDevelop-extensions/files/3394670/Extension.zip)


I still need to find how to avoid them stacking/syncing together when they get stuck. 🤔

**Comment by 4ian** [comment]
Can you describe the issue or better send me a game with the issue? Should not be too hard to debug then :)

**Comment by PascalLadalle** [comment]
The issue was that if I put 2 objects on the scene, one 10px away from a wall, and another 50px away from a wall, they didn't collide with the wall at the same time, but they moved away from it at the same time.
It took two additional properties, but I fixed it! 
Latest version:
[Extension.zip](https://github.com/4ian/GDevelop-extensions/files/3414726/Extension.zip)

**Comment by 4ian** [comment]
Looks nice :) I guess this may not work with very slow speed of movement at the object can be considered as stuck? But otherwise looks good. Will add it!

**Comment by 4ian** [comment]
Finally added (after renaming it to Timed Back and Forth Movement)! Thanks for making this behavior 👍
