### ISSUE TITLE
Stats.js Loader

### ISSUE THREAD

**Issue by FlokiTV** [4ian/GDevelop-extensions#149]
## Describe the extension
A simple way to load stats.js for development

## Checklist

- [x] Extension has a proper name and description.
- [x] Extension has tags (for example: "platform, brick, breakable").
- [x] All behaviors have a description.
- [x] All functions (actions, conditions, expressions) have descriptions.
- [x] I confirm that this extension can be intergrated to this GitHub repository, distributed and MIT licensed.

[statsjs-Extension.zip](https://github.com/4ian/GDevelop-extensions/files/6478745/statsjs-Extension.zip)

**Comment by arthuro555** [comment]
I would have some suggestions for improvements:
- 1. Rename it to FPS Counter: The average GDevelop user doesn't know what stat.js is, naming it FPS Counter is more straightforward.
- 2. No need to make the users decide when to load stats.js, you can just copy paste all the code from stats.min.js into a "onFirstSceneLoaded" callback function to avoid 
  - 1. Relying on the network
  - 2. Relying on the user to not unnecessarily reload it
  - 3. Making sure it is loaded before using the function
- 3. The `stats.update()` method is called using `requestAnimationFrame`, which show the Browser FPS but not the GDevelop FPS. Put a global reference to the object somewhere (for example `gdjs._statsjs`) and update it in "onScenePreEvents" to show the amount of FPS the GDevelop game actually has.
- 4. You can also add support for the milliseconds panel of stats.js by using the `begin` method in onScenePreEvents and `end`method in onScenePostEvents instead of the `update` method. [See the official example](https://github.com/mrdoob/stats.js/#usage).

**Comment by tristanbob** [comment]
I created a trello card for this.  I think it would be very valuable to have a way to show gamedevs the current status of game in real-time:  resources used and values of common settings.
https://trello.com/c/xjapezMV/115-statistics-and-debug-info

**Comment by FlokiTV** [comment]
Thank you guys, I'll work on this tool 🔧

**Comment by 4ian** [comment]
Thanks all! I was also thinking of integrating https://github.com/ErikSom/gamestats which seems a bit more adapted to games. Could almost be part of the game engine, or I could update the GDevelop profiler to hook into this :)

> Put a global reference to the object somewhere (for example gdjs._statsjs) and update it in "onScenePreEvents" to show the amount of FPS the GDevelop game actually has.

Yes please! It's important to use the same method as GDevelop for updating.

**Comment by FlokiTV** [comment]
Nice alternative, I'll try the `gamestats` 🤝

**Comment by 4ian** [comment]
Thanks @FlokiTV! Let me know if it works too :) 
If it works, it would be awesome. Follow the recommendations of @arthuro555, I think they would apply the same.

If it works well, we could rework the extensions to allow arbitrary files to be added (rather than putting the source in `onFirstSceneLoaded`). I could also improve the `gdjs.Profiler` so that you can "plug" gamestats into it (meaning that we would get information about the time to render, the time to run events and the time to run behaviors!).

**Comment by arthuro555** [comment]
Something semi-related that would be cool would be to add "profile builds" that would be like a release build but with the profiler and that sends the profile data to the GDevelop services for the developer to inspect in the game services section of the IDE.

**Comment by FlokiTV** [comment]
Hmm a tool to collect statistics from users? Cool idea

**Comment by FlokiTV** [comment]
I will work hard on this. Thank you for letting me collaborate. I'm very excited 💻🚀
