### ISSUE TITLE
Change cursor style

### ISSUE THREAD

**Issue by Bouh** [4ian/GDevelop-extensions#16]
## Describe the extension
This extension add an action for changing the style of your cursor. 
Value can be : 
default, pointer, help, progress, wait, cell, crosshair, text, move, grab, grabbing, not-allowed, zoom-in, zoom-out

List of all cursors can be found here :
https://developer.mozilla.org/fr/docs/Web/CSS/cursor

I've added the most important in description.
## Checklist

- [x] Extension has a proper name and description.
- [x] Extension has tags (for example: "platform, brick, breakable").
- [x] All behaviors have a description.
- [x] All functions (actions, conditions, expressions) have descriptions.
- [x] I confirm that this extension can be intergrated to this GitHub repository, distributed and MIT licensed.

## Extension file

[Extension_cursor.zip](https://github.com/4ian/GDevelop-extensions/files/3490184/Extension_cursor.zip)

**Comment by 4ian** [comment]
Thanks! I've added this :)
Remember to always:
* Use PascalCase for extension names. Don't include extension in the extension name. It's implicit.
* Give a name to the function, even if there is only one. Games events will be stored using the function name.
* Don't set parameters description that are too long. Prefer adding a longer description that will better fit on the UI.
* No space before the ":" in English.
* Put links to english documentation pages so that everyone can read them.

Apart from that, looks good. I made the fixes and added this 👍
