### ISSUE TITLE
Extend variables support

### ISSUE THREAD

**Issue by Bouh** [4ian/GDevelop-extensions#2]
## Describe the extension
This extentions add : 
Conditions :
 - Global variable exist
 - Scene variable exist
 - Object variable exist
 
 Actions :
 - Delete global variable
 - Delete scene variable

String expressions: 
 - Format time second to HH:MM:SS
 - Get text from clipboard

All of theses use Javscript events.

## Checklist

- [x] Extension has a proper name and description.
- [x] Extension has tags (for example: "platform, brick, breakable").
- [x] All behaviors have a description.
- [x] All functions (actions, conditions, expressions) have descriptions.
- [x] I confirm that this extension can be intergrated to this GitHub repository, distributed and MIT licensed.

## Extension file

[Extend_variables.zip](https://github.com/4ian/GDevelop-extensions/files/3202641/Extend_variables.zip)

**Comment by 4ian** [comment]
Nice :) 
I will probably make an extension "Extended variables support" and have two others: "FormatTime" (or TimeFormatting) and "PasteFromClipboard"

In your JS, be careful of using delete on variables though. It's something internal, so that will break as soon as I change this (and that *will* happen). Instead, use `remove`: http://4ian.github.io/GD-Documentation/GDJS%20Runtime%20Documentation/gdjs.VariablesContainer.html#remove
In general, even if JavaScript allow you to "see" everything, you must forbid any usage of things that are starting with underscore, or any long chain of accessors (`something.somethingElse.hey.stop.please`) which are a sign that you're looking "too depth" in the object. Instead, use methods that are well commented, and as possible documented.

A documented method, which is not marked as `@private` is supported and will probably work for a long time ;)

**Comment by Bouh** [comment]
I know remove(), I tested it but if I use it the variables remain visible in the debugger.

**Comment by 4ian** [comment]
Fair enough, they should be considered removed after calling remove, but it's true that they are still showing in the debugger UI. This is because they are kept in memory, to avoid garbage. But this probably won't be useful at all.
So we could change "remove" so that it really is deleting variables from the container.

**Comment by Bouh** [comment]
I've fixed my functions with **remove()**
[Extend_variables.zip](https://github.com/4ian/GDevelop-extensions/files/3212740/Extend_variables.zip)

**Comment by 4ian** [comment]
Thanks! :) Let me do some changes so that JavaScript functions can get access to the context of the events function, to read the parameters easily :)
Should simplify your life :D 

Also I've seen you're not declaring variables with `var`. This is "tolerated" in JavaScript, but actually quite dangerous because this means that you're declaring a global variable.
I'm going to add "use strict" internally to the new JavaScript events from now on so that such things are warned/errored. Should also improve performance :)

**Comment by 4ian** [comment]
I've added all of your functions into 3 extensions : ExtendedVariables, Clipboard and TimeFormatter. They will surely be very useful! 😄

You can also see that I've exposed "eventsFunctionContext", that allow to access to the arguments and set the return value. It allow to massively simplify the functions :D

Thanks for submitting them!
