### ISSUE TITLE
New extension

### ISSUE THREAD

**Issue by Official-IceCreeperPE** [4ian/GDevelop-extensions#63]
An extension that can fade in and out and is really useful for when you want to make a scene fade in then next scene fade out.

Checklist

- [x] Extension has a proper name and description: Yes
- [x] Extension has tags (for example: "platform, brick, breakable"): Yes
- [x] All behaviors have a description: Yes
- [x] All functions (actions, conditions, expressions) have descriptions: Yes
- [x] I confirm that this extension can be intergrated to this GitHub repository, distributed and MIT licensed: Yes, I Agree

Extension file link: http://www.mediafire.com/file/872gr4ejhm0a6qn/Fade.json/file

Thanks >.<
~ItsIceCreeperPE

**Comment by 4ian** [comment]
Hi! 

I wondered at some point about making a FadeIn/FadeOut behavior, but:
- There is the tween behavior that can be used, and is more flexible.
- We could still have a "Fade" extension, with a behavior for each object type, but in this case it should not have in its description mention of "Scene transition" or even the scene, because it's up to the user of the extension to do whatever they want with it. Also, it would need a property to configure the speed of disappearance I think, and maybe a checkbox to choose if the object should be deleted at the end of a fade out.

**Comment by GustavoMarciano** [comment]
something like a "screen transition" would be interesting

**Comment by GustavoMarciano** [comment]
> Hi!
> 
> I wondered at some point about making a FadeIn/FadeOut behavior, but:
> 
> * There is the tween behavior that can be used, and is more flexible.
> * We could still have a "Fade" extension, with a behavior for each object type, but in this case it should not have in its description mention of "Scene transition" or even the scene, because it's up to the user of the extension to do whatever they want with it. Also, it would need a property to configure the speed of disappearance I think, and maybe a checkbox to choose if the object should be deleted at the end of a fade out.

something like a "screen transition" would be good
ct js has a feature called transitions that is very interesting, it makes games look more polished
[https://cdn.discordapp.com/attachments/490054623747506196/686697867921981451/ezgif.com-gif-maker.gif](url)

**Comment by arthuro555** [comment]
I think that #84 (Flash and transitions painter) would do what was described. I would reject this extension as it is "outperformed" by that other one.
