### ISSUE TITLE
Shaking camera extention

### ISSUE THREAD

**Issue by westboy31** [4ian/GDevelop-extensions#65]
## Description
Shaking camera effect useful for impact effect or earthquake effect.
Extention allows you to:
* Call shaking camera action in X axis and Y axis with diffrents powers. (when you assign 0 power it's static on the axis).
* Action reset the last position of camera before shaking. (this for who work with static camera if camera has its own behavior we just need to put the action after the other actions controlling the camera).

## Checklist
- [*] Extension has a proper name and description.
- [*] Extension has tags (for example: "platform, brick, breakable").
- [] All behaviors have a description.
- [*] All functions (actions, conditions, expressions) have descriptions.
- [*] I confirm that this extension can be intergrated to this GitHub repository, distributed and MIT licensed.

## Extension file
[ShakingCamera.zip](https://github.com/4ian/GDevelop-extensions/files/5488753/ShakingCamera.zip)

## Exemple file
[exemple shaking camera.zip](https://github.com/4ian/GDevelop-extensions/files/5488764/exemple.shaking.camera.zip)

**Comment by 4ian** [comment]
Nice! Thanks for the example file, that's very very useful :) 

I've just added it to the registry. Main change that I've done is to switch all variables to use a single "structure" variable: `_CameraShaking`, using the layer name and the camera index as children, to contain the initial position.
This is because otherwise, shaking two layers at the same time would have confused the extension, and a layer camera would have been positioned back to the initial position of something else.

We also can not use "Trigger Once", because it works only for the event, not for each distinct layer. Instead, we must check if the shaking is not being done for the specified layer and camera index, using the structure variable :)

I've done a few other minor changes:

* "Power" of shake => "Amplitude"
* Use long description for additional details for parameters.
* Use the `Layer (text)` parameter type instead of a string for layers :) 
* "The number of Camera" => Prefer: "The camera index (0 by default)"

Thanks for submitting this!
