### ISSUE TITLE
Colour Conversions Extension

### ISSUE THREAD

**Issue by Add00** [4ian/GDevelop-extensions#88]
## Describe the extension
A simple extension that converts rgb values into other colour formats.

## Checklist

- [x] Extension has a proper name and description.
- [x] Extension has tags (for example: "platform, brick, breakable").
- [x] All behaviors have a description.
- [x] All functions (actions, conditions, expressions) have descriptions and proper sentences.
- [x] I've followed the best practices listed on http://wiki.compilgames.net/doku.php/gdevelop5/extensions/best-practices
- [x] I confirm that this extension can be intergrated to this GitHub repository, distributed and MIT licensed.

## Extension file
[colourConversions.zip](https://github.com/4ian/GDevelop-extensions/files/5748902/colourConversions.zip)

**Comment by 4ian** [comment]
Great idea :) This is overall looking good, I have multiple nitpickings so that the extension reach an almost perfect state:

A few feedbacks:
- Use USA English for names and PascalCase for the extension name: `ColorConversion`
- In tags: hexidecimal => `hexadecimal`. Add `color`. Don't use plural: `conversion`
- Period at the end of sentences: `Convert RGB color values into various other colour formats and vice versa.`
- Let's use "invert-colors" for the icon :)
- For `name to RGB`, either use an explicit object containing the values, or remove the function. We don't use as much as possible CSS/getComputedStyle/getPropertyValue. It's implementation specific and it forces to create a div, which will create memory pressure on the garbage collector and is super inefficient. Basically never ever use DOM manipulation for games.
- Always use triple equal everywhere in JavaScript: `minRGB == maxRGB` => `minRGB === maxRGB`. Never use `==`.
- Nitpicking: `let H = 0` => `let h = 0` (use camelCase for variables, not PascalCase).
- For RgbToHex, please use `gdjs.rgbToHex` ;) See https://docs.gdevelop-app.com/GDJS%20Runtime%20Documentation/gdjs.html#.rgbToHex
- For HexToRgb: 
  - you have a useless variable: `const n = eventsFunctionContext.getArgument("n"); let hex = n;`. Just name your parameter "hex".
  
Finally, for all functions can you verify what is going on if you enter an invalid value as a parameter? Thanks! :)

**Comment by Add00** [comment]
Thanks for taking the time to review my extension. I think I've added all your feedback so let me know what you think.

- I've changed all spellings to there American counterparts.
- Fixed the spelling and grammar mistakes that were pointed out.
- Swapped the extension icon.
- Originally I used a switch statement for the `NameToRgb` function, so I reverted the code back to that version to be more efficient.
- For several functions (HSL and HSV) I found more efficient algorithms (courtesy of Stack Overflow) and replaced the old ones.
- Swapped out `RgbToHex` with the built in method.
- Lastly, I added input validation to each function, though I'm not sure what to, put for the error message.
  - Right now I have place holder text there since I'm not sure what the message content should be.

[colorConversion.zip](https://github.com/4ian/GDevelop-extensions/files/5758493/colorConversion.zip)

**Comment by 4ian** [comment]
Thanks! Looks great :) 
I've fixed a few grammar mistakes ("an" => "a"), added periods, and changed the error handling so that all errors are logged in the console, and a default value is returned (black in all cases, i.e: "0;0;0").

> Right now I have place holder text there since I'm not sure what the message content should be.

Usually, I choose something like `console.error("Unable to do blabla:", error)` with `error` being the exception or the message describing what went wrong.

Thanks for working on this! :)
