### ISSUE TITLE
New extension - FireBullet update

### ISSUE THREAD

**Issue by PascalLadalle** [4ian/GDevelop-extensions#97]
A user complained that he couldn't shoot multiple bullets, so I edited the extension to allow that, by moving the timer reset to post-events.
Ahh, if modifying GDevelop was as easy as that 😅 

[NewFireBulletExtension.zip](https://github.com/4ian/GDevelop-extensions/files/5845774/NewFireBulletExtension.zip)

**Comment by 4ian** [comment]
Interesting! :) What do you mean by multiple bullets? Like using the action multiple time to fire different kind of bullets, but at the same time?

The idea of the behavior is to have a cooldown so that you can't fire too much bullets. Might be also a good idea to recommend the user to add multiple times the behavior to its object: once per bullet type! This way, you can fire different bullets at different time, with still the fire rate you chose for each! :) 

Let me know if that make sense?

> Ahh, if modifying GDevelop was as easy as that 😅

Seems like extensions are a good first step then 😄

**Comment by 4ian** [comment]
> I was able to add the same behavior twice, but I'm unable to find both actions in the action list, only one shows 

You can but you have to bring the full editor, so that you can choose the behavior :)
![image](https://user-images.githubusercontent.com/1280130/105409643-a6b10b80-5c28-11eb-8103-25d2fd4aa22e.png)

Though as you mentioned, this won't work for behaviors that use timer or object variables, so most of them including this one!.. You have to rely exclusively on something else: the behavior properties, which are guaranteed to be one per each different behavior, even if you have the same more than once.

Ideally we would have something analyzing your behavior, to tell that as soon as a scene/object variable or timer is used, the behavior is limited to one per object (but this is the case in most objects).
And we could also introduce behavior timers!

> At first, I wanted to give a unique name to the timer to allow multiple bullets, but I wasn't sure how, and the post-events solution popped up and seemed good enough for the purpose.
> Is there something wrong with it?

It's a workaround I would say, but seems fine enough for the purpose indeed.

> Yeah, but the UI is what I would like to work on. 😊 I tried to look at the internals once, because I had worked with flexbox once for a website, and I think GD uses that, but I was quite unable to figure out... anything. So many components embedded together, and I can hardly read javascript, so I was completely lost.

Yes it's better to know a bit of React, because all the interface are made up of components. Be sure to use the [React developer tools](https://chrome.google.com/webstore/detail/react-developer-tools/fmkadmapgofadopljbjfkapdkoienihi?hl=en) in Chrome that can help you identify which component is under the cursor. 

But it's a good idea to read a primer about JavaScript and React.

**Comment by 4ian** [comment]
Updated 👍
