### ISSUE TITLE
Floating multitouch button (New extension)

### ISSUE THREAD

**Issue by tristanbob** [4ian/GDevelop-extensions#98]
## Describe the extension

An area of the screen that acts like a button when touched.  Supports multitouch.

Select an area of the screen to detect touches.
When a touch starts in this area, the property "IsPressed" will be true until that touch ends.
Optionally, draw a border around the touch area and a circle that follows the active touch.

## Checklist

- [x] Extension has a proper name and description.
- [x] Extension has tags (for example: "platform, brick, breakable").
- [x] All behaviors have a description.
- [x] All functions (actions, conditions, expressions) have descriptions and proper sentences.
- [x] I've followed the best practices listed on http://wiki.compilgames.net/doku.php/gdevelop5/extensions/best-practices
- [x] I confirm that this extension can be integrated to this GitHub repository, distributed and MIT licensed.

## Extension file

[FloatingMultitouchButtonExtension-0.0.1.json.zip](https://github.com/4ian/GDevelop-extensions/files/5847226/FloatingMultitouchButtonExtension-0.0.1.json.zip)

## Example game

https://games.gdevelop-app.com/game-4e320516-f9d3-4f24-9926-da0b6bdd7b69/index.html
(Touchscreen devices only)

[MultiTouchButtons.zip](https://github.com/4ian/GDevelop-extensions/files/5847230/MultiTouchButtons.zip)
(Example game source)

## Request for help

This extension has a major problem; only the first listed object will detect touches.  If I change the order of objects in the object panel, it is always the first one that works.   In my example game, you can see this by deleting the objects one at a time.  

Does anyone know why this is happening?

**Comment by 4ian** [comment]
> Does anyone know why this is happening?

I think this is because, unfortunately, the "A new touch has started" (and "ended" version too) is not "idempotent". Each time you call them, they "consume" one of the new touch. This is because it was done to allow you test multiple times (in a "while" event) during the same frame, in case more than one touch started during the frame (if I put two fingers on the screen, the internal list of "new touches" for this frame will have two touches. Then when I use the condition "A new touch has started", one will be consumed. `LastTouchId` will return this first touch. If you call the condition again, it will be true, but `LastTouchId` will now return the second touch id).

This design is not great because while it's in the description, it's too implicit. I'd like to find another way to handle multiple touches like this.

**Comment by 4ian** [comment]
This means that for now, there is no great way to handle what you want to do... I would have to offer for the next version of GDevelop a new way of checking the touch identifiers that have started!

**Comment by tristanbob** [comment]
Heh, it reminds me of the Heisenberg uncertainty principle.  I guess we can close this issue for now and I'll look for future updates to the GDevelop multitouch system. 

I might start a new issue for a standard (non-multitouch) button, using much of the same code.
